spring.application.name=crudoperation

spring.datasource.url=jdbc:mysql://localhost:3306/StudentTable
spring.datasource.username=root
spring.datasource.password=harshad@123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
